### ISSUE TITLE
Visibility issues with Dr Racket and dark themes

### ISSUE THREAD

**Issue by pmplant** [racket/drracket#235]
Some elements of the UI, particularly the error message in the lower left, are difficult to see on a dark theme. I could not any way to customise these elements under preferences.

![screenshot at 2018-10-21 16-02-16](https://user-images.githubusercontent.com/20781382/47324727-e2a63200-d615-11e8-8600-a57768f4427c.png)

**Comment by winny-** [comment]
Related racket/racket#2140

**Comment by aidalgol** [comment]
Following on from the discussion in racket/racket#2140, I do not think this is a racket/gui bug, because I get the correct colours with a minimal racket/gui application:
```racket
#lang racket/gui

(let* ((frame (new frame%
                   [label "Dark GTK bug"]))
       (readout (new message%
                     [parent frame]
                     [label "Message"]))
       (button (new button%
                    [parent frame]
                    [label "Button"])))
  (send frame show #t))
```

**Comment by aidalgol** [comment]
I'm having a really hard time finding where in the (DrRacket) code these problem widgets are created, so I'm quite stuck in debugging this myself.

**Comment by rfindler** [comment]
One issue is whether or not `racket/gui` is providing the information that says that dark-on-light mode is enabled.

You are right that the controls that have the wrong font and colors are not standard GUI controls. But they are implemented here: https://github.com/racket/gui/blob/master/gui-lib/mrlib/name-message.rkt

**Comment by aidalgol** [comment]
The problem does seem to be in the MrLib widgets.  The "Name Message" widget in this program will is rendered in black.
```racket
#lang racket/gui

(require mrlib/name-message)

(let* ((frame (new frame%
                   [label "Dark GTK bug"]
                   [width 640]
                   [height 480]))
       (message (new message%
                     [parent frame]
                     [label "Message"]))
       (button (new button%
                    [parent frame]
                    [label "Button"]))
       (name-msg (new name-message%
                      [parent frame]
                      [label "Name Message"])))

  (send frame show #t))
```

**Comment by aidalgol** [comment]
@rfindler Are they all `name-message`s?  Even the line:column readout, and memory usage readout?  What about the "Run", "Debug", etc buttons?

**Comment by rfindler** [comment]
The line:column and memory usage bits are in framework/private/frame, the Run/Debug buttons are mrlib/switchable-button.

**Comment by sorawee** [comment]
The color of error messages of Check Syntax is fixed by f50868afa47921b7e4c074615a37ba918ecf7724.

**Comment by rfindler** [comment]
Thanks, @sorawee !

**Comment by sorawee** [comment]
@rfindler do you want me to keep posting outstanding issues about dark mode here?

**Comment by rfindler** [comment]
I'm happy with posts wherever you find convenient. Pointing me to specific ones is very helpful, however you find easiest. (I recently turned my OS to dark mode so maybe I'll just find them on my own too, as I find time to poke around.)

**Comment by sorawee** [comment]
1. [General dark mode] Tabs have a bad contrast

<img width="829" alt="Screen Shot 2019-12-09 at 07 47 09" src="https://user-images.githubusercontent.com/9099577/70450182-247f7b00-1a58-11ea-8f72-ae132a3b973d.png">

2. [General dark mode] Selection by highlighting with blue has a bad contrast. Note that the black text on grey background looks subpar but readable enough for me, but other people might have issues with that.

   By the way, I'm not sure if "selection by highlighting with blue" in this fashion is user friendly and "standard". It's not clear that each language level is clickable/choosable. I thought there are various standard selection widgets. Is it a good idea to switch to those instead?

<img width="304" alt="Screen Shot 2019-12-09 at 07 51 37" src="https://user-images.githubusercontent.com/9099577/70450814-39a8d980-1a59-11ea-8589-2dcbca522eec.png">

3. [All dark themes] DrRacket link is too dark blue. The language information and memory limit are also kinda hard to read.

<img width="517" alt="Screen Shot 2019-12-09 at 08 10 20" src="https://user-images.githubusercontent.com/9099577/70452123-72e24900-1a5b-11ea-8172-9c4f1a4dcce3.png">

4. [All dark themes] `in:` is black, so it completely disappears on dark background

<img width="478" alt="Screen Shot 2019-12-09 at 08 13 05" src="https://user-images.githubusercontent.com/9099577/70452357-d8ced080-1a5b-11ea-9491-d6fdf34484a8.png">

5. [All dark themes] Yet another too dark blue in macro stepper

<img width="594" alt="Screen Shot 2019-12-09 at 08 15 32" src="https://user-images.githubusercontent.com/9099577/70452561-2c411e80-1a5c-11ea-872f-a445ec4a8611.png">

**Comment by sorawee** [comment]
6. Most textbox still has white background.

<img width="713" alt="Screen Shot 2019-12-09 at 08 25 36" src="https://user-images.githubusercontent.com/9099577/70453473-ab832200-1a5d-11ea-8243-473fbacdeef4.png">

I think this is how it's supposed to be 

<img width="394" alt="Screen Shot 2019-12-09 at 08 26 41" src="https://user-images.githubusercontent.com/9099577/70453485-b2aa3000-1a5d-11ea-9365-70dddbbebf97.png">

**Comment by jackfirth** [comment]
I'm using dark mode on a mac as well, so I just wanted to say thank you @sorawee for hunting down all these contrast issues and reporting them!

**Comment by jackfirth** [comment]
Here's one: the signature box arrow semi-circle thing is very bright.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/8175575/70512610-c351b900-1ae4-11ea-9d50-2ba6d0c0c2f6.png">

**Comment by sorawee** [comment]
Here's one more issue.

Green on blue is hard to read already. Current line highlight on green on blue is even more so.

<img width="385" alt="Screen Shot 2019-12-11 at 02 50 31" src="https://user-images.githubusercontent.com/9099577/70615541-6ed03b80-1bc1-11ea-8dbd-714f6ac68e30.png">

**Comment by sorawee** [comment]
Black text on black background:

<img width="483" alt="Screen Shot 2019-12-18 at 07 40 07" src="https://user-images.githubusercontent.com/9099577/71100355-bc244e00-2169-11ea-859f-ce663b4299f7.png">

**Comment by sorawee** [comment]
Another black text on dark background. Note that the red highlight is also pretty bad.

<img width="555" alt="Screen Shot 2019-12-18 at 07 43 32" src="https://user-images.githubusercontent.com/9099577/71100618-33f27880-216a-11ea-8491-f24a5308ff7e.png">

**Comment by sorawee** [comment]
This might not be an issue, but I find the yellow background too bright for dark mode and looks out of place.

<img width="252" alt="Screen Shot 2019-12-18 at 07 45 02" src="https://user-images.githubusercontent.com/9099577/71100735-6603da80-216a-11ea-8e5d-b32f68cb9192.png">

<img width="1280" alt="Screen Shot 2019-12-18 at 07 46 57" src="https://user-images.githubusercontent.com/9099577/71100866-9a779680-216a-11ea-8408-50b835a434a1.png">

**Comment by rfindler** [comment]
Matthew fixed the tab color https://github.com/racket/gui/pull/153 .

**Comment by rfindler** [comment]
Another one: the teaching languages test report pane. To see, run `(check-expect 1 2)` in, say, BSL.

**Comment by rfindler** [comment]
@sorawee when you write "[General dark mode] Selection by highlighting with blue has a bad contrast. Note that the black text on grey background looks subpar but readable enough for me, but other people might have issues with that." I think that that's a choice made at the level of the operating system -- at least I see that blue there too on my mac os machine, until I change the "Highlight Color" setting in the "General" pane of "System Preferences" (available via the apple menu).

**Comment by sorawee** [comment]
Yep, you are right.

Note that I just realized that the choose language popup's background is semi-transparent, so if we have a dark theme like white on black, the text will be really unreadable.

<img width="304" alt="Screen Shot 2019-12-25 at 13 02 20" src="https://user-images.githubusercontent.com/9099577/71450442-d8e6f580-2716-11ea-9510-7799bc40ef1a.png">

**Comment by rfindler** [comment]
I think that part is fixed already.

**Comment by rfindler** [comment]
@sorawee re "Green on blue is hard to read already. Current expression highlight on green on blue is even more so.", I was thinking that the green and blue colors were a bit too saturated and so I've adjusted them and here's how something like the screenshot you used above looks now:

<img width="267" alt="Screen Shot 2019-12-25 at 8 41 39 PM" src="https://user-images.githubusercontent.com/399024/71454575-10759200-2757-11ea-9b89-3d88561707d3.png">

Does that fix the problem, would you say?

**Comment by rfindler** [comment]
I kind of like the yellow/black configuration how it stands out but if someone wants to make some concrete suggestions I could change them.

I think @rmculpepper should probably address the macro-stepper color issue (using `color-prefs:add-color-scheme-entry` and `color-prefs:lookup-in-color-scheme`) as I don't really have a good sense of how color is supposed to work there.

Other than that, I think I've fixed stuff for the rest of the comments here. Did I miss anything that you notice @sorawee @jackfirth @shhyou ?

**Comment by sorawee** [comment]
Is there a way to test these changes easily? Usually I would install a snapshot, but it won't build until tomorrow, correct?

**Comment by rfindler** [comment]
Probably it is easiest is to build yourself or install a snapshot (unless you're on windows, in which case waiting for a snapshot is easiest).

**Comment by shhyou** [comment]
Looks pretty nice!

Here are some random observations:

* There's a (perhaps rarely used) Check Syntax feature highlighting syntax errors in gold. Maybe it could be `DarkGoldenrod` or `Goldenrod` in dark mode.
<img width="311" alt="drr-white-on-black-3" src="https://user-images.githubusercontent.com/1910898/71487185-a523d280-27df-11ea-9e54-8ec4cf11c3d2.png">


* The text color in Racket → Limit Memory dialog seems to be hard-wired.
<img width="567" alt="drr-white-on-black-4" src="https://user-images.githubusercontent.com/1910898/71487221-e5835080-27df-11ea-87aa-98e75bc8a3ee.png">



* The tab names have higher contrast in light mode. It's a bit difficult to see file names.
<img width="484" alt="drr-white-on-black-1" src="https://user-images.githubusercontent.com/1910898/71487042-bfa97c00-27de-11ea-81aa-85dbaa5fc341.png">

**Comment by rfindler** [comment]
Thanks! I've fixed the first two, but the third one is something we'd have to change in https://github.com/MiMo42/MMTabBarView .

**Comment by shhyou** [comment]
Thanks!

> but the third one is something we'd have to change in https://github.com/MiMo42/MMTabBarView .

Indeed, it's not configurable and has been using `NSColor.selectedTextBackgroundColor` for inactive tabs since the beginning.

**Comment by rfindler** [comment]
If you understand well enough to make a pull request we could probably get a new version of the library built and put into the distro.

**Comment by sorawee** [comment]
I just downloaded the today's snapshot. Here are more feedback. Note that I think a lot of these are going to be wontfix or not easily fixable, but let me report them anyway:

- White background issue:
    - "About DrRacket" dialog

        <img width="857" alt="Screen Shot 2019-12-26 at 16 27 37" src="https://user-images.githubusercontent.com/9099577/71494616-48cfab80-27fd-11ea-9a82-a3a48f729675.png">

    - Syntax object in the REPL

        <img width="595" alt="Screen Shot 2019-12-26 at 16 37 21" src="https://user-images.githubusercontent.com/9099577/71494716-09ee2580-27fe-11ea-927e-3c0bcac5b544.png">

    - GC icon

        <img width="99" alt="Screen Shot 2019-12-26 at 16 41 19" src="https://user-images.githubusercontent.com/9099577/71494793-c6e08200-27fe-11ea-9197-41d053e365a4.png">

- Debug mode
    - White background issue
    - Black labels on dark background
    - White stepping buttons

    <img width="1280" alt="Screen Shot 2019-12-26 at 16 40 27" src="https://user-images.githubusercontent.com/9099577/71494805-e37cba00-27fe-11ea-8e7f-e6bda951d2dc.png">

- Stepper mode for beginning students
    - White background issue
    - Black label on dark background (`1/2`)

    <img width="693" alt="Screen Shot 2019-12-26 at 16 46 06" src="https://user-images.githubusercontent.com/9099577/71494875-55ed9a00-27ff-11ea-8d55-2ee9d024b210.png">

    Incidentally, the "lambda step back" and "lambda step forward" icons clearly have a really low resolution. Can we fix this too?

- FrTime: white background
    <img width="357" alt="Screen Shot 2019-12-26 at 16 50 39" src="https://user-images.githubusercontent.com/9099577/71494954-e88e3900-27ff-11ea-960c-cb48b4e5c267.png">

- pict/code: completely transparent background makes some character disappear

    <img width="113" alt="Screen Shot 2019-12-26 at 16 54 04" src="https://user-images.githubusercontent.com/9099577/71495064-aa454980-2800-11ea-89e9-912d15cd9313.png">

**Comment by sorawee** [comment]
Another white background issue: `read` in the REPL 

<img width="620" alt="Screen Shot 2019-12-26 at 17 05 07" src="https://user-images.githubusercontent.com/9099577/71495264-f1800a00-2801-11ea-9e25-904cd73465c7.png">

**Comment by rfindler** [comment]
I'm having trouble making a recycle icon on a black background. The current ones are recycle@2x.png and recycle.png in https://github.com/racket/icons/ .

**Comment by rfindler** [comment]
I think the pict/code one is the expected behavior and probably shouldn't change.

**Comment by rfindler** [comment]
@rmculpepper : it looks like the simplest/best way to make `mrlib/syntax-browser` look right in dark modes is to have it depend on the framework (specifically to get access to `color-prefs:`). Is that a problematic dependency, do you think?

**Comment by sorawee** [comment]
Various boxes (comment box, XML box, text box, etc.)
- The blinking caret is black, so it can't be seen on the dark background.
- For text box, the text is black, so it can't be seen on the dark background.
- Low resolution icon (minor)
- Icon has white background (minor)
<img width="146" alt="Screen Shot 2019-12-27 at 05 48 28" src="https://user-images.githubusercontent.com/9099577/71519526-be269500-286c-11ea-968d-8a124cce70f0.png">

**Comment by rfindler** [comment]
With branch day imminent, what should get fixed here to be in the release?

After a bunch of false starts I think I have a path forward for syntax snips. The macro stepper seems important too. Anything else?

**Comment by shhyou** [comment]
> > - The tab names have higher contrast in light mode. It's a bit difficult to see file names.
> > <img src="https://user-images.githubusercontent.com/1910898/71487042-bfa97c00-27de-11ea-81aa-85dbaa5fc341.png">
>
> Thanks! I've fixed the first two, but the third one is something we'd have to change in https://github.com/MiMo42/MMTabBarView .

For reference: this is hopefully fixed by MiMo42/MMTabBarView#74 and merged in racket/libs@743b813.

**Comment by shhyou** [comment]
What is the color scheme entry for the stack frame background (background of `(cdr x)` in the above screenshot)?

I added a `framework:failed-background-color` entry in [this commit](https://github.com/shhyou/drracket-scheme-dark-green/commit/716d611c4cb94b51204e178a86141c5eaf24eb39#diff-809e10b1260e14bbd78cebc4e39dee73R18), but that one does not do the job.

**Comment by rfindler** [comment]
@shhyou looks like it isn't in a color scheme. It is the result of `get-error-color` in drracket/private/debug.rkt. Probably that should change to use the color scheme!

**Comment by sorawee** [comment]
@rfindler very weird. I just installed snapshot "20200115-738d2b7" and the blue link of DrRacket is still dark blue (not fixed), while the language name and mode is now light green (fixed).

<img width="477" alt="Screen Shot 2020-01-15 at 22 47 00" src="https://user-images.githubusercontent.com/9099577/72500250-f58fbe00-37e8-11ea-855b-e3b8261aee5d.png">

**Comment by rfindler** [comment]
@sorawee what OS are you using?

**Comment by rfindler** [comment]
Also, the code in question that determines the color is the function `click-delta` in drracket/private/rep.rkt, which calls `gui-utils:get-clickback-delta` passing along `(preferences:get 'framework:white-on-black?)`. It might be good to know what some printfs inside `gui-utils:get-clickback-delta` and that tell us what the preference is returning for you. It isn't obvious to me what's going wrong.

**Comment by sorawee** [comment]
OK. I know now what's going on.

Here's the classic theme.

<img width="473" alt="Screen Shot 2020-01-16 at 13 45 10" src="https://user-images.githubusercontent.com/9099577/72565326-76d96600-3866-11ea-8c69-f6eb7087e968.png">

Here's what happens when I switch to white on black theme.

<img width="472" alt="Screen Shot 2020-01-16 at 13 46 30" src="https://user-images.githubusercontent.com/9099577/72565407-9ec8c980-3866-11ea-8bbe-9643f94b2b73.png">

Here's what happens after I click "Run" to reset the REPL window.

<img width="474" alt="Screen Shot 2020-01-16 at 13 46 53" src="https://user-images.githubusercontent.com/9099577/72565453-bacc6b00-3866-11ea-8ade-b4406134bb09.png">

And here's what happens after I open a new tab

<img width="470" alt="Screen Shot 2020-01-16 at 13 47 51" src="https://user-images.githubusercontent.com/9099577/72565559-f2d3ae00-3866-11ea-9956-a24fba985e49.png">

So the problem seems to be that the configuration is not updated immediately in various places, and there are also multiple levels of the update event.

**Comment by rfindler** [comment]
Oh yes, that's expected (and unfortunate).

**Comment by rfindler** [comment]
Although the dark issues for DrRacket aren't all done, I think I'm going to close this issue now. Lets open new issues for whatever remaining issues there are.

**Comment by jackfirth** [comment]
Now that I'm actually using 7.6, I just wanted to say that dark mode looks _really_ good. Thank you all!
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8175575/74584182-42032080-4f84-11ea-975e-2a78bda8cd4c.png">

**Comment by sleepnova** [comment]
I have the same problem. If you keep DrRacket open on MacOS, the text color will be wrong when the system theme is changed from "Light Mode" to "Dark Mode" or vise-versa. The text on the toolbar and bottom(such as memory usage) is difficult to read.

**Comment by rfindler** [comment]
Unfortunately this is the way it currently is. Many of the light/dark
places react immediately, some react on a new window and some react only on
restart. (It is an issue for sure! Just not on anyone's list to fix at the
moment as far as I know.)

Robby

**Comment by jcolivo** [comment]
Hello Racket Team,
I appreciate all the hard work on trying to improve the dark mode in DrRacket. Thank you.

Just hoping that you won't forget us Windows users. ;-)
My issues are as pointed out in this thread: [https://groups.google.com/forum/#!topic/racket-dev/xYjE9JCe9u0](https://groups.google.com/forum/#!topic/racket-dev/xYjE9JCe9u0)

If there is anything I can do to help (I'm not a programmer, but can certainly help with testing), please let me know. 

Have a wonderful weekend!

**Comment by rfindler** [comment]
Yeah, the windows situation isn't great. I think that basically all of the problems there can be traced to not knowing how to implement this function under windows:

https://docs.racket-lang.org/mrlib/White_on_Black_Panel_Predicate.html

If you have knowledge of windows internals or the strength to dig through the various google results on the topic and come up with something, that would be huge!

**Comment by jcolivo** [comment]
I certainly would like to contribute. While I'm not a software engineer (just a simple-minded microeconomist), I can start looking around to see what solutions are viable; plus, I'm curious about this kind of development. 

Wish me luck.

**Comment by default-kramer** [comment]
> Yeah, the windows situation isn't great. I think that basically all of the problems there can be traced to not knowing how to implement this function under windows:
> 
> https://docs.racket-lang.org/mrlib/White_on_Black_Panel_Predicate.html
> 
> If you have knowledge of windows internals or the strength to dig through the various google results on the topic and come up with something, that would be huge!

The docs on `white-on-black-panel-scheme?` say "This predicate is intended to determine if the underlying operating system is in a “dark” mode." Despite being a regular Windows user, I didn't know that Windows had such a setting until I googled it just now and found this: https://www.cnet.com/how-to/how-to-enable-dark-mode-in-windows-10/

@rfindler , is the desired behavior on Windows 10 that `white-on-black-panel-scheme?` looks at that "Choose your default app mode" setting (see cnet link above)? Because I would not have expected that setting to have any effect on DrRacket. I thought that all the coloring decisions were based on the Edit -> Preferences -> Colors menu in DrRacket.

If you want the "Choose your default app mode" setting, I'm pretty sure that I can find it in the Windows registry somewhere. (In fact, this looks like it: https://stackoverflow.com/questions/51334674/how-to-detect-windows-10-light-dark-mode-in-win32-application) I can try to make a PR for mrlib if this is the desired behavior. I don't have any older versions of Windows handy, so it will likely support Win10 only.

**Comment by alex-hhh** [comment]
The registry key `AppsUseLightTheme` in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`, will be 1 or missing if applications use the "light" theme and will be 0 if the applications should use a dark theme.  

I verified that `AppsUseLightTheme` changes to 0 if I select "dark" mode in my preferences on my Windows 10 machine.  The key is missing if "Dark" mode was never selected on a machine.

`white-on-black-panel-scheme?` could just look for this key on Windows?

Source: https://stackoverflow.com/questions/51334674/how-to-detect-windows-10-light-dark-mode-in-win32-application

**Comment by rfindler** [comment]
Maybe we need a new PR/Issue for this specific problem?

@default-kramer the operating system controls the drawing of the system controls (like buttons and menus and panels). DrRacket controls other things (like the editor window).

**Comment by rfindler** [comment]
Hi Alex: I think that's a great start. (I think we probably also want
testing to know which versions of Windows it works on.)

**Comment by mflatt** [comment]
More ideas for dark mode on Windows based on various undocumented flags and functions: https://github.com/mflatt/gui/commit/fd38e768670c46975fbaba3ca6f8db145c0e4bd3

Last time I looked at this, I concluded that system Win32 control classes like buttons or checkboxes (I forget which, but I think it was buttons) don't support dark mode.

**Comment by jcolivo** [comment]
I only have access to 64 bit Windows 10, so I can help with testing on that system.

As for Windows 7 and 8, dark mode was never supported on those versions except within later versions of Google Chrome and via 3rd party software modding (please correct me if I am wrong); therefore, I think Windows 10-only support for dark mode would be perfectly fine, and even expected by users of older Windows versions.  

It's interesting that there were issues with Win32 control classes. I wonder if they have been fixed in the recent Windows 10 updates? I'm looking around for clues.

**Comment by sleepnova** [comment]
Don't know if this could help? A code snippet to listen to mode change events on MacOS.
https://github.com/LinusU/DarkModeListener

**Comment by rfindler** [comment]
That's helpful! But I would guess that the bulk of the problem is making sure that all of the places that have drawing that depends on the wob/bow state properly get send redraw requests when the drawing changes (and that that drawing state is properly consulted at the right time (not, eg, when an object is created, say, but when it is drawn). With the current code, it is just an issue of going through all of the places one by one and looking for things to fix. :(

**Comment by jcolivo** [comment]
I found the Windows Registry Key as @default-kramer mentioned above referencing the StackOverflow thread:
[https://stackoverflow.com/questions/51334674/how-to-detect-windows-10-light-dark-mode-in-win32-application](url)

> If you want the "Choose your default app mode" setting, I'm pretty sure that I can find it in the Windows registry somewhere. (In fact, this looks like it: https://stackoverflow.com/questions/51334674/how-to-detect-windows-10-light-dark-mode-in-win32-application) I can try to make a PR for mrlib if this is the desired behavior. I don't have any older versions of Windows handy, so it will likely support Win10 only.

On my system (64 bit Windows 10, latest version), I verified the location of the registry key:
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`

This is a screenshot of the key when light theme is chosen. Notice the ApsUseLightTheme value set at 0x00000001 (1)
![Light Theme On](https://user-images.githubusercontent.com/7208522/83310151-b9c22780-a1d0-11ea-9478-c7a2c8f1e77c.jpg)

This is a screenshot of the key when dark theme is chosen. Notice the ApsUseLightTheme value now set at 0x00000000 (0)
![Light Theme Off](https://user-images.githubusercontent.com/7208522/83310212-e2e2b800-a1d0-11ea-85d1-567b573b230d.jpg)

Would this feature require Racket code to look for this specific registry key value, or would the code be written at a lower level?

**Comment by sorawee** [comment]
Here's one more issue:

<img width="406" alt="Screen Shot 2020-07-12 at 08 11 11" src="https://user-images.githubusercontent.com/9099577/87250037-55bd9080-c417-11ea-8b30-a62283ffa7d8.png">

The last "Extra regexp" somehow has white background, though only on characters.

**Comment by rfindler** [comment]
This issue is a bit of a mess because it has so many different things going on and many of them are already fixed.

I'm going to create a new racket/gui issue and copy windows issues over there and create a new issue for @sorawee 's recent comment and then just close this one.
