### ISSUE TITLE
Creation of compiled/drracket directory in a read-only system directory

### ISSUE THREAD

**Issue by jsmaniac** [racket/drracket#47]
### What version of Racket are you using?
6.4.0.15 (20160330-bcacb34)

### What program did you run?
```
#lang typed/racket
```

The error also occurs with

```
#lang datalog
```

And with:

```
#lang racket/base
(module m racket/base
  (require typed/racket))
```

`#lang racket` and `#lang racket/base` work fine.

### What should have happened?

When pressing F5, the interactions window should appear, with the REPL for that language.

### If you got an error message, please include it here.

Instead the following error is printed:
```
../../nix/store/1d9nd30pxir2hiskzvdzihwb77gmwkvm-racket-6.4.0.15/share/racket/collects/compiler/cm.rkt:358:0: make-directory: cannot make directory
  path: /nix/store/1d9nd30pxir2hiskzvdzihwb77gmwkvm-racket-6.4.0.15/share/racket/pkgs/typed-racket-lib/typed-racket/compiled/drracket
  system error: Read-only file system; errno=30
```

### Does the same program work in the command-line `racket` tool?

The `typed/racket` REPL works fine using the command-line tool:
```
racket -I typed/racket
Welcome to Racket v6.4.0.15.
> (+ 1 1)
- : Integer [more precisely: Positive-Index]
2
> 
```

**Comment by jsmaniac** [comment]
The only call to `make-directory` in [cm.rkt](https://github.com/racket/racket/blob/master/racket/collects/compiler/cm.rkt#L448) is:

```
    (with-compiler-security-guard (make-directory* code-dir))
```

And @rfindler changed `code-dir`'s definition recently, maybe it's related to that change?

**Comment by rfindler** [comment]
Yes, definitely related.

Is this a snapshot build?

**Comment by jsmaniac** [comment]
@rfindler Yes, a source build of `https://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-6.4.0.15-src.tgz`, the bug occurs with the pre-built-packages tarball too.

**Comment by rfindler** [comment]
I've pushed something that just gives up trying to put .zo files into directories that are not writeable. This seems like it can get into trouble if you ever open and modify a file that one of those files depends on (as those .zo files will be wrong and yet still used), and this can happen if you do something like "raco pkg update --clone <pkg>" of some pkg where you put the cloned version of it in a writeable place. But hopefully that's not what's happening here.

Here's the commit. Tomorrow's build should have it and in the meantime you can uncheck the language dialogs "populate compiled directories" checkbox (click "show details" to make it appear).

https://github.com/racket/drracket/commit/737329561e41f55c0d2b5b38927636b286f8556e

**Comment by rfindler** [comment]
(I've closed this, but feel free to re-open if there are further problems.)

**Comment by jsmaniac** [comment]
Thanks! I'll try it when it comes out.

**Comment by jsmaniac** [comment]
@rfindler: The problem is still there with today's nightly (20160403-794061b), but it got worse as now even `#lang racket` and `#lang racket/base` don't work. They both give the following error:

```
../../nix/store/w2y4qp7dmjy4g4hsxcz411qy2m6y6b3g-racket-6.4.0.15/share/racket/collects/compiler/cm.rkt:358:0: make-directory: cannot make directory
  path: /nix/store/w2y4qp7dmjy4g4hsxcz411qy2m6y6b3g-racket-6.4.0.15/share/racket/collects/racket/compiled/drracket
  system error: Read-only file system; errno=30
```

The directory is read-only, though, as reported by `ls`:
```
> ls -ld /nix/store/w2y4qp7dmjy4g4hsxcz411qy2m6y6b3g-racket-6.4.0.15/share/racket/collects/racket/compiled/                                                                                                             ~
dr-xr-xr-x 2 root nixbld 8192 1970-01-01 01:00 /nix/store/w2y4qp7dmjy4g4hsxcz411qy2m6y6b3g-racket-6.4.0.15/share/racket/collects/racket/compiled/
> ls -ld /nix/store/w2y4qp7dmjy4g4hsxcz411qy2m6y6b3g-racket-6.4.0.15/share/racket/collects/racket/                                                                                                                      ~
dr-xr-xr-x 15 root nixbld 4096 1970-01-01 01:00 /nix/store/w2y4qp7dmjy4g4hsxcz411qy2m6y6b3g-racket-6.4.0.15/share/racket/collects/racket/
```

If I uncheck "Populate `compiled/` directories", it works fine. Won't this cause poor performance, though? Shouldn't DrRacket use the already-populated 'compiled/' directories, if it can't populate `compiled/drracket`?

**Comment by rfindler** [comment]
Wow, I sure messed that commit up! I've tried again, this time with better testing. Hopefully it won't make things worse this time.
